project_id = "trtuqzdsutmindcjbkvj"

[functions.initialize-admission-payment]
verify_jwt = false

[functions.verify-admission-payment]
verify_jwt = false

[functions.initialize-acceptance-payment]
verify_jwt = false

[functions.verify-acceptance-payment]
verify_jwt = false

[functions.send-offer-letter]
verify_jwt = true

[functions.send-admission-notification]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.accept-offer]
verify_jwt = false

[functions.track-application]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.create-student]
verify_jwt = true

[functions.export-users]
verify_jwt = true

[functions.update-user-password]
verify_jwt = true

[functions.send-bulk-email]
verify_jwt = true

[functions.send-bulk-sms]
verify_jwt = true

[functions.create-school]
verify_jwt = true

[functions.create-school-admins]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.send-fee-reminders]
verify_jwt = true

[functions.create-parent-account]
verify_jwt = false

[functions.initialize-fee-payment]
verify_jwt = false

[functions.verify-fee-payment]
verify_jwt = false

[functions.delete-parent-account]
verify_jwt = false

[functions.paystack-reconcile]
verify_jwt = true

[functions.send-report-cards]
verify_jwt = true

[functions.notify-absentees]
verify_jwt = false

[functions.register-staff]
verify_jwt = false
